### ISSUE TITLE
Watching too many files - this might cause high cpu usage

### ISSUE THREAD

**Issue by arty-name** [ChrisWren/grunt-nodemon#46]
Hi,

I have just updated to 0.3.0 and I started getting following error in the console: 

> [nodemon] watching 32,903 files - this might cause high cpu usage. To reduce use "--watch".

I do have `watch` configured: 

    options: {
        watch: ['backend', 'conf/app'],

So I don't know whether it was always broken without warning, or it is broken now with the upgrade.

**Comment by jdoose** [comment]
Same here. The start/initialization of nodemon takes very long. It occurs in the referenced nodemon version 1.2.0. It is fixed in 1.3.0-5 with a quicker start up / enumeration of file sin watch()

Update to nodemon 1.3.0-5 would be great!

**Comment by rbecheras** [comment]
Nodemon 1.3.0 doesn't exists, but 0.4.0 does and fix the issue.
