### ISSUE TITLE
How can I watch just one folder?

### ISSUE THREAD

**Issue by HelloCui** [ChrisWren/grunt-nodemon#53]
I have a grunt task(not serve). It just need to watch one folder. But **Options.watch** is use to set the **additional folders**. And it's not beautiful if I hardcode all other folders to **Options.ignore**. I try to set 
```
ignore : ['./**']
```
but fail. Changes still trigger restart. How should I set the Options?
There is a little question confuse me: If  it's default to watch all files, what kind of folder should be added to the  Options.watch?

**Comment by Wortex17** [comment]
I have the very same problem and am wondering as well

**Comment by ChrisWren** [comment]
Have you tried setting watch to an array with one string like this?

```
watch: ['myFolder']
```

Here is the documentation for nodemon: https://github.com/remy/nodemon#monitoring-multiple-directories.

I think the doc wording in grunt-nodemon's README might be out of date, as `watch` appears no longer to be additional folders, rather only the ones specified in `watch`. I will update the README, sorry for inconvenience.

**Comment by ChrisWren** [comment]
Closing as I updated the README.
