### ISSUE TITLE
Prevent nodemon from executing on first run

### ISSUE THREAD

**Issue by foxx** [ChrisWren/grunt-nodemon#56]
Currently nodemon will execute the `-x` commands when it is first ran. This is undesirable in some cases, and I'd like to propose a new flag to prevent this, perhaps `--no-first-run`. Thoughts?

**Comment by ChrisWren** [comment]
What does that flag do, didn't see it in nodemon docs after a search? Feel free to make a PR.

**Comment by foxx** [comment]
Sorry, this is so embarrassing, I raised this issue on the wrong repo!!
